# Java 17 异常相关知识点

# 思维导图

![image-20211227073900912](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227073900912.png)

对于一个程序来说，理想的状态下，是都能正确运行的， 但是总会因为软件和硬件的原因出现一些不可避免的异常以及错误。但是，在实际的开发中将不可能这么的理想，不按规则的数据和有问题的业务代码，在 Java 中是如何处理这些异常和错误的呢？我们来看一看。



# Throwable

该类是 Java 语言中所有错误和异常的父类，只有是此类的实例， 或者此类的子类的对象才会被 Java 虚拟机当做异常或者错误抛出，当然也可以使用显式的语句触发。

他的直接子类包含两个， 一个是 Error（错误），另一个是 Exception（异常）。通常用来包含程序发生了异常情况。

为了在编译时检查对应的异常，对于 Throwable 的对象和其任何的子类， 只要不是 RuntimeException 和 Error 的子类， 都会被编译器视为已经检查了异常信息。

并且在这些实例中的异常对象都是在上下文中新创建的， 用来包含对应的相关的错误信息，以及堆栈的跟踪数据。

该类的定义是：

```java
public class Throwable implements Serializable 
```

定义的构造方法：

![image-20211227095844036](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227095844036.png)

| **修饰符** | **构造函数**                                                 | **描述信息**                                                 |
| ---------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
|            | Throwable()                                                  | 构造一个 throwable 对象，使用 null 作为其详细信息。          |
|            | Throwable(String message)                                    | 构造一个可 throwable 对象，使用 message 作为其详细的信息。   |
|            | Throwable(String message, Throwable cause)                   | 构造一个可 throwable 对象，使用一个 message 和 cause 作为详细信息。 |
| protected  | Throwable(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) | 构造一个可 throwable 对象，使用 message 和 cause 作为详细信息，并指定是否开启 suppression 和 是否开启可写堆栈跟踪。 |
|            | Throwable(Throwable cause)                                   | 构造一个可 throwable 对象，使用用指定的message 和 cause (cause==null ? null: cause. tostring())，它通常包含cause的类和详细信息。 |

除了构造函数， 还有对应的方法。

![image-20211227075111661](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227075111661.png)

演示案例：

![image-20211227082456770](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227082456770.png)

# Error

对于 Error 类， 它是 Throwable 的子类，主要代表的含义是，对于正常的运行程序不应该尝试去捕获的严重问题。大多数情况错误是异常情况，或者开发者无法控制的情况， 比方说， 运行需要内存， 内存不足了。 程序肯定无法正常运行，程序存储需要空间， 硬盘没有空间了，程序也有出现问题。

对于一个方法不需要在它的 throws 语句中声明，并且在方法执行期间可能抛出，但是没有捕获的 Error 的任何子类。 因为这些错误是不应该发生的异常情况，在编译器编译时检查的时候，Error 及其子类也会被视为未经检查（unchecked）的异常。因为它的不可预料性，所以大多数情况下无法捕获到。可以尝试使用系统级别被识别。

Error 的定义:

```java
public class Error extends Throwable
```

![image-20211227095617263](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227095617263.png)

该类对应的构造函数。

![image-20211227095922019](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227095922019.png)

查看源码发现并没有扩展的方法，只有构造函数。

![image-20211227100136008](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227100136008.png)

并且所有的构造函数都调用了父类的构造函数。

常见的错误信息有： IOError， LinkageError（NoClassDefFoundError），虽然 LinkageError 不常见， 但是 NoClassDefFoundError 在初学的时候， 不使用 IDE 的情况下还是容易出现的。

在虚拟机（JVM ） 加载 class 的时候，而没有找到对应的 class 报出的错误，注意和 ClassNotFoundException 的区别， 一个是异常， 一个是错误。

常见的错误 Error 有：

- NoClassDefFoundError ( 找不到 class 定义的错误 ）。
- OutOfMemoryError（内存溢出的错误 ）。
- StackOverflowError（ 堆栈溢出的错误 ）。

# Exception

对于 Exception 以及其子类，同样的继承 Throwable 类，它可以使用应用程序本身的程序捕获对应的异常信息。

对于 Exception 异常， 包含两种类型：

- 检查类型（checked） 

- 非检查类型（unchecked）。

对应的是 RuntimeException 及其子类非检查异常 ***UncheckedException***，另外一种不包含 RuntimeException 的检查类型异常***CheckedException***。

常见的非检查异常（UncheckedException）有：

- Nullpointer Exception （ 空指针异常 ）。
- ClassCastException（ 类型强制转换异常 ）。
- IllegalArgumentException（ 传递非法参数异常 ）。
- IndexOutOfBoundsException（ 下标越界异常 ）。
- NumberFormatException（ 数值类型转换异常 ）。
- ArrayIndexOutOfBoundsException（ 数组下标越界异常 ）。
- ArrayStoreException（ 数据存储异常，操作数组时类型不一致 ）。
- ArithmeticException（ 算术异常 )。
- BufferOverflowException（ 缓冲区溢出异常 )。

常见的检查异常（CheckedException）有：

- IOException （ IO 操作异常）。
- SQLException （ SQL 操作语句异常）
- ClassNotFoundException （ 类找不到的异常 ）。

除了以上的还有很多很多异常和错误的信息， 详细的可以参看 Error 和 Exception 的子类及子子...类。

# 异常的捕获

上面介绍了基础的异常和错误信息， 知道了错误的异常无法捕获，而异常信息检查类的异常都需要进行捕获，对于非检查类的异常多数是由程序员编写的代码存在bug，而出现的。而检查类的需要使用捕获的语法try{}catch(){}。

语法定义：

```java
try{
	//需要抛出检查类型异常的执行内容
}catch(Exception ex){
	// ex 的信息
}
```

对于需要捕获的异常都需要使用 throws 抛出。 例如如下代码:

```java
// Class 中的 forName 方法
public static Class<?> forName(String className)
                throws ClassNotFoundException
```

使用该方法的时候就需要捕获异常。 

```java
try {
	Class.forName("ExceptionTest");
} catch (ClassNotFoundException ex) {
	System.out.println(ex.getMessage());
}
```

正确的情况下不会提示任何错误， 编译运行都无异常。 

![image-20211227114423108](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227114423108.png)

这个时候， 我们修改对应的 ExceptionTest 为 ExceptionTest2。然后在运行测试。

![image-20211227114925762](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227114925762.png)

可以使用 printStackTrace()打印对应的错误信息， 调试的时候使用比较多， 线上运行项目不会使用该方法。

这里发现异常使用的场景， ClassNotFoundException 类没有找到的异常。 其中会有对应的异常信息。并且查看其异常的定义。

```java
public class ClassNotFoundException extends ReflectiveOperationException
```

而 ReflectiveOperationException 又继承了 Exception ，该类的定义如下:

```java
public class ReflectiveOperationException extends Exception 
```

![image-20211227115526429](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227115526429.png)

# 如何使用自定义的异常

从上面的观察可以发现想要使用一个异常只要继承 Exception 类即可。或者继承 RuntimeException 类。

举例，定义一个自定义的异常类 CustException 继承自 Exception 类，并定义对应的构造函数。

```java
public class CustException extends Exception {

    public CustException() {
    }

    public CustException(String message) {
        super(message);
    }

    public CustException(Throwable cause) {
        super(cause);
    }

    public CustException(String message, Throwable cause) {
        super(message, cause);
    }

    public CustException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
    
}
```

编写测试类。 因为继承自 Exception 所以需要显示的捕获异常才可以。如果不显示的捕获异常，编译会出现错误。

![image-20211227120631808](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227120631808.png)

修改正常使用的情况

![image-20211227121059250](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227121059250.png)

如果不想显式的抛出异常，就需要继承 RuntimeException 类。

代码如下：

![image-20211227121440520](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227121440520.png)

然后测试运行：

![image-20211227121601298](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227121601298.png)

这里没有显示的使用 throws 。 也没有捕获对应的异常。但是程序不会出现变异错误。但是在运行的时候， 需要需要因为运行异常导致业务无法往下走的问题。

举例说明，修改传入的参数改为 “2”：

![image-20211227121913047](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227121913047.png)

这里演示了为 null 以及 type = "2" 的情况， 都是会出现异常。 所以这个时候，就需要捕获。这种实际在工作中， 会在最上层进行捕获， 展示给用户的不是一段异常代码就好。

![image-20211227122122122](https://cdn.jsdelivr.net/gh/xymiao/xymiaocdn/res/2021/202112/image-20211227122122122.png)

本篇文章， 主要说说 Java 中的异常信息， 对于异常的代码多数都是 Java 1.7 之前的知识点。希望能够给你代码一点帮助。 

感谢您的阅读， 收藏， 点赞， 关注。

说会话这些基础的知识点， 就应该花个功夫，深入一下， 这样你的体系就会建立起来。 不会因为项目中学习的知识体系出现断层。学习技术最快的方式是实战， 而学习技术体系最全的是书籍，当然官方的文档更好更新。因为第一手资料也很重要。 但是需要有一个知识高度，最起来要知道哪些知识在实际工作中基本上不会用， 学了更好， 不学也不会影响当下的你。只能祝你早日找到适合自己的学习方式。更上一层楼。